### PR TITLE
fix #262: permit nested cfn intrinsics like !Not [!Equals ]

### LINKED ISSUE #262: iidy render `!Not [!Equals ]` produces invalid YAML for CloudFormation
### Expected
Input Template untouched

### Actual
Template pre-processed unexpectedly and CloudFormation is not happy with it.

### Input Template

```
Conditions:
  CreateAlarms: !Equals [ !Ref CreateAlarms, "yes" ]
  InitialNoop: !Equals [ !Ref CodePath, "initial-noop" ]
  CreateStreamAlarms: !Equals [ !Ref CreateAlarms, "yes" ]
  InVpc:
    !Not [!Equals [!Ref VpcStackName, "" ]]
```

### Result

```
❯ iidy render invalid_expansion.yml
Conditions:
  CreateAlarms: !Equals
    - !Ref CreateAlarms
    - 'yes'
  InitialNoop: !Equals
    - !Ref CodePath
    - initial-noop
  CreateStreamAlarms: !Equals
    - !Ref CreateAlarms
    - 'yes'
  InVpc: !Not
    _data:
      - !Ref VpcStackName
      - ''
    visited: false
    ctor: !<tag:yaml.org,2002:js/function> |-
      class AnonTag extends Tag {
              constructor() {
                  super(...arguments);
                  this.tag_name = tag_name;
              }
          }
    tag_name: Equals
```

### PR DESCRIPTION
**Pull request by tavisrudd**

### CODE REVIEW

File: src/yaml.ts [hunk 1]
```diff
@@ -33,6 +35,9 @@ const schemaTypes: jsyaml.Type[] = [];
 export const customTags: {[key: string]: typeof Tag} = {};
 export const cfnIntrinsicTags: {[key: string]: typeof Tag} = {};
 
+export const isCustomIidyTag = (tag: Tag): boolean => !!customTags[tag.tag_name];
+export const isCfnIntrinsicTag = (tag: Tag): boolean => !!cfnIntrinsicTags[tag.tag_name];
```
Comment (kalupa) [inline src/yaml.ts:39]: this is just a personal preference. These days I find explicit casting to be more readable:

```suggestion
export const isCfnIntrinsicTag = (tag: Tag): boolean => Bool(eancfnIntrinsicTags[tag.tag_name]);
```

There's potential for small performance loss, but I'm assuming this isn't something that needs to be highly optimized anyway.

File: src/preprocess/visitor.ts [hunk 2]
```diff
@@ -163,8 +163,10 @@ export class Visitor {
     } else {
       if (_.isArray(node.data)
         && node.data.length === 1
-        && node.data[0] instanceof yaml.Tag) {
+        && node.data[0] instanceof yaml.Tag && ! yaml.isCfnIntrinsicTag(node.data[0])) {
```
Comment (kalupa) [inline src/preprocess/visitor.ts:166]: still like that extra space, eh? 😉

**Review by kalupa — APPROVED** [review]
