### PR TITLE
fix #213: bug in resource node preprocessing

### LINKED ISSUE #213: Can't use preprocessor tags on "global" sections
I'm building a series of stacks with common components, and to save rewriting almost the same large templates with minimal changes, I considered splitting each component's configuration/templates into separate files, and using `!$merge` to bring them all together as/when needed on a per-stack basis.

Consider this extremely cut-down example to illustrate what I'm trying to achieve here;

**file1.yml**
```
Resources:
  MemcachedCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      Engine: memcached
```

**file2.yml**
```
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
```

**stack.yml**
```
$imports:
  memcached: ./file1.yml
  database: ./file2.yml

$defs:
  CustomResources:
    VPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 172.30.0.0/16
```

So if **stack.yml** contains the following (to illustrate the pre-processor is working and configured correctly);;
```
merged: !$merge
  - !$ CustomResources
  - !$ database.Resources
  - !$ memcached.Resources
```

The output becomes;
```
$ iidy render stack.yml
merged:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 172.30.0.0/16
  PublicSubnetA:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
  DatabaseInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: postgres
  MemcachedCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      Engine: memcached
```

However, if the section `merged` is replaced with `Resources`;
```
Resources: !$merge
  - !$ CustomResources
  - !$ database.Resources
  - !$ memcached.Resources
```

then the following error is observed;
```
$ iidy render stack.yml
error Invalid resource type: undefined at Root.Resources: [
 {
  "_data": "OtherResources"
 },
 {
  "_data": "database.Resources"
 },
 {
  "_data": "memcached.Resources"
 }
]  
```

Is there any way to run this kind of merge/preprocessor logic on the top-level "Global" sections to allow this kind of configuration to work and render correctly?

### PR DESCRIPTION
**Pull request by tavisrudd**

### CODE REVIEW

File: src/preprocess/visitor.ts [hunk 1]
```diff
@@ -637,6 +637,9 @@ export class Visitor {
 
   // Special handling for CloudFormation `Resource` entries and iidy custom Resource templates.
   visitResourceNode(node: any, path: string, env: Env): AnyButUndefined {
+    if (node instanceof yaml.Tag) {
+      return this.visitResourceNode(this.visitNode(node, appendPath(path, '$Preprocess'), env), path, env);
```
Comment (jpb) [inline src/preprocess/visitor.ts]: Could this use the tag name rather than `$Preprocess` here?

If this is a CloudFormation tag (instead of an iidy one) would `visitNode` essentially be a no-op?

Comment (tavisrudd) [reply src/preprocess/visitor.ts]: 1) I suppose so. I'll do that.
2) Yep

Comment (jpb) [reply src/preprocess/visitor.ts]: So if it were a CloudFormation tag, would it produce a loop here?

Comment (tavisrudd) [reply src/preprocess/visitor.ts]: Yeah, it would be a bug in that case anyway. We could check explicitly for `iidy` custom tags and fail hard if it's not one.

**Comment by dannosaur** [comment]
From the test templates that I have that demonstrated the fault, this fixes the problem with `Resources` being a `!$merge` tag.

File: src/preprocess/visitor.ts (hunk 1 above)
Comment (tavisrudd) [reply src/preprocess/visitor.ts]: I just pushed some protection against that.

**Comment by tavisrudd** [comment]
Done
