### PR TITLE
Fix non-octal numeric strings in the middle of string

### LINKED ISSUE #126: Handling of non-octal strings with leading zeros is incorrect when interpolated into another string
```
$ cat octal.yaml
$defs:
  num: '0012345'

foo: "a {{ num }} b"

$ iidy render octal.yaml
foo: a '0012345' b
```

Expected:

```
foo: a 0012345 b
```

Related to #69

### PR DESCRIPTION
**Pull request by jpb**
Fixes #126

### CODE REVIEW

File: src/yaml.ts [hunk 1]
```diff
@@ -198,5 +198,8 @@ export const dump = (doc: object): string =>
   jsyaml.safeDump(doc, {schema: schema, lineWidth: 999})
     .replace(/!<!([^>]+?)>/g, '!$1')
     .replace(/ !\$include /g, ' !$ ')
-    .replace(/\$0string \s*(0\d+)/g, "'$1'");
-// $0string ^ is an encoding added in preprocess/index.ts:visitString
+    .replace(/: \$0string (0\d+)$/gm, ": '$1'")
```
Comment (tavisrudd) [inline src/yaml.ts]: @jpb I missed the colon first time I looked at this. It makes sense now.
