### PR TITLE
Handle empty `update-stack --changeset` gracefully

### LINKED ISSUE #66: `iidy update-stack --changeset` fails when there are no changes
Expected no-op message and exit with status code 0, actual:

```
$ iidy --region us-west-2 update-stack --changeset stack-args.yaml
Stack Details:
 Name:                    foo
 Status                   CREATE_COMPLETE
 Capabilities:            CAPABILITY_IAM
...

Stack Template Diff:

info: Templates are the same


Command Metadata:
 CFN Operation:           CREATE_CHANGESET
 Region:                  us-west-2
...
error: The submitted information didn't contain changes. Submit different information to create a change set. Deleting failed changeset.
```

### PR DESCRIPTION
**Pull request by jpb**
Fixes #66

### CODE REVIEW

File: src/cfn/index.ts [hunk 1]
```diff
@@ -1358,7 +1362,12 @@ export async function updateStackMain(argv: GenericCLIArguments): Promise<number
 
     const createChangesetResult = await changeSetRunner.run();
     if (createChangesetResult > 0) {
-      return createChangesetResult;
+      if (changeSetRunner._hasChanges) {
```
Comment (tavisrudd) [inline src/cfn/index.ts]: If we're going to use this property outside of the class we should remove the underscore which signals privateness.
